version: "3.7"
services:
  app:
    build:
      context: ./backend-laravel-api
      dockerfile: Dockerfile
    image: news
    container_name: news-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend-laravel-api:/var/www
    networks:
      - news
      
  react-ui:
    build:
      context: ./react-news-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: news-react-ui
    stdin_open: true
    volumes:
       - ./react-news-app:/usr/src/app/react-app
       - /usr/src/app/react-app/node_module
    tty: true
    networks:
      - news

  db:
    image: mysql:8.0
    container_name: news-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./backend-laravel-api/docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - news

  nginx:
    image: nginx:alpine
    container_name: news-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./backend-laravel-api:/var/www
      - ./backend-laravel-api/docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - news

networks:
  news:
    driver: bridge