version: '3.7'

services:

  backend:
    build:
      context: ./backend-laravel-api
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/backend-laravel-api
    volumes:
      - ./backend-laravel-api:/var/www/backend-laravel-api
    ports:
      - "8000:8000"
    depends_on:
      - appdb
    networks:
      - app
      - db

  frontend:
    build:
      context: ./react-news-app
      dockerfile: Dockerfile
    tty: true
    working_dir: /var/www/react-news-app
    volumes:
      - ./react-news-app:/var/www/react-news-app
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app

  appdb:
    image: mysql:8.0.32
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "news_db"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PASSWORD: "root"
    volumes:
      - .dbdata:/var/lib/mysql/
    ports:
      - 3306:3306
    networks:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: appdb
      MYSQL_ROOT_PASSWORD: "root"
    depends_on:
      - appdb
    ports:
      - 8443:80
    networks:
      - db

networks:
  app:
    driver: bridge
  db:
